// POSTS
export const FETCH_POSTS = "FETCH_POSTS";
export const SUCCESS_FETCH_POSTS = "SUCCESS_FETCH_POSTS";
export const FAILED_FETCH_POSTS = "FAILED_FETCH_POSTS";
export const SEND_NEW_POST = "SEND_NEW_POST";
export const SUCCESS_SEND_NEW_POST = "SUCCESS_SEND_NEW_POST";
export const ADD_COMMENT = "ADD_COMMENT";
export const SUCCESS_ADD_COMMENT = "SUCCESS_ADD_COMMENT";
