// POSTS
export const FETCH_POSTS = "FETCH_POSTS";
export const SUCCESS_FETCH_POSTS = "SUCCESS_FETCH_POSTS";
export const FAILED_FETCH_POSTS = "FAILED_FETCH_POSTS";
export const SEND_NEW_POST = "SEND_NEW_POST";
export const SUCCESS_SEND_NEW_POST = "SUCCESS_SEND_NEW_POST";
export const ADD_COMMENT = "ADD_COMMENT";
export const SUCCESS_ADD_COMMENT = "SUCCESS_ADD_COMMENT";
export const SUCCESS_AUTH = "SUCCESS_AUTH";
export const AUTH = "AUTH";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_INITIATE_LOGOUT = "AUTH_INITIATE_LOGOUT";
export const CHECK_AUTH_TIMEOUT = "CHECK_AUTH_TIMEOUT";
export const AUTH_CHECK_STATE = "AUTH_CHECK_STATE";
export const FETCH_USERS = "FETCH_USERS";
export const SUCCESS_FETCH_USERS = "SUCCESS_FETCH_USERS";
